# Generated by Django 3.2.6 on 2021-08-25 07:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Date_time', models.DateTimeField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Fee', models.FloatField(blank=True, default=0.0, null=True)),
                ('Fee_Coin', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('Editor', 'Editor'), ('Artist', 'Artist'), ('Admin', 'Admin')], max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format '123456789' ", regex='^[0-9]+$')])),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
