# Generated by Django 3.2.6 on 2021-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210825_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kineto_Kisom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('trackname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('net_royalty_total', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Trade_Data',
        ),
    ]
