# Generated by Django 3.2.6 on 2021-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rbt_mar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaFonte_MAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICE_ID', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('COUNTRY', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ARTIST_DISPLAY', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('TRACK_TITLE', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('NET', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
